name: benchmark

on:
  push:
    branches:
      - extend-benchmarks

permissions:
  # deployments permission to deploy GitHub pages website
  deployments: write
  # contents permission to update benchmark contents in gh-pages branch
  contents: write

env:
  CARGO_TERM_COLOR: always
  cache_path: |
    p2panda-rs/target
    ~/.cargo
  cargo_manifest: p2panda-rs/Cargo.toml

jobs:
  p2panda-rs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Restore from cargo cache
        uses: actions/cache@v2
        with:
          path: ${{ env.cache_path }}
          key: ${{ runner.os }}-tarpaulin-${{ hashFiles('**/Cargo.toml') }}

      - name: Setup cargo-criterion
        run: cargo install cargo-criterion

      - name: Run criterion suite
        run: cargo criterion --manifest-path ${{ env.cargo_manifest }} --output-format bencher | tee output.txt

      - name: Store benchmark results
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: p2panda-rs criterion benchmark
          tool: 'cargo'
          output-file-path: output.txt
          auto-push: false

      - name: Deploy Github pages
        run: git push 'https://p2panda:${{ secrets.GITHUB_TOKEN }}@github.com/p2panda/p2panda.git' gh-pages:gh-pages
