name: Build and test

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  rust-test:
    name: p2panda-rs
    uses: p2panda/p2panda/.github/workflows/rust-setup.yml@clippy-ci

    steps:
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose
