name: Build and test

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  rust-fmt:
    name: p2panda-rs
    uses: p2panda/p2panda/.github/workflows/rust-setup.yml@clippy-ci

    steps:
      - name: Check formatting
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check
