name: Run tests and warm cache for p2panda-rs

on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always
  cache_path: |
    p2panda-rs/target
    p2panda-rs/Cargo.lock
    ~/.cargo
  cargo_manifest: p2panda-rs/Cargo.toml

jobs:
  rust-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: clippy, rustfmt
          override: true

      - name: Restore from cargo cache
        uses: actions/cache@v2
        with:
          path: ${{ env.cache_path }}
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}

      - name: Run tests and warm cache
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path ${{ env.cargo_manifest }}
